AllCops:
  RunRailsCops: true
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - bin/**/*
    - node_modules/**/*
Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 7
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Next:
  Enabled: false
Style/GlobalVars:
  AllowedVariables: [$flipper]
